---
services:
  database:
    image: mysql:8.3
    container_name: database
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: db_client
      MYSQL_PASSWORD: ${MYSQL_DB_CLIENT_PASSWORD}
    restart: unless-stopped
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: db_client
      DB_PASSWORD: ${MYSQL_DB_CLIENT_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
    restart: unless-stopped
...
